{% set name = "paragraph" %}
{% set version = "1.2.1" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b202701a79d24468dc0c75f59d21007012e1115edf9ca5d8e67a2938ee4daa1f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - attrs >=18.1.0

test:
  imports:
    - paragraph


about:
  home: https://github.com/Othoz/paragraph
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A pure Python micro-framework supporting seamless lazy and concurrent evaluation of computation graphs.'
  description: |
    In essence, the package allows to write functional code directly in
    Python: statements merely specify relationships among variables
    through operations. Evaluation of any variable given the values of
    other variables is then de facto:
  
      * lazy: only operations participating in the determination of the requested value are executed,
      * concurrent: operations can be executed by a thread pool of arbitrary size.
    
    In addition, relationships among variables can be traversed in
    both directions, allowing a form of backpropagation of information
    through the computation network that would be cumbersome to
    implement in an imperative manner.
  doc_url: http://paragraph.readthedocs.io/en/latest/
  dev_url: https://github.com/Othoz/paragraph

extra:
  recipe-maintainers:
    - pbourguignon
